# Generated by Django 6.0.3 on 2026-03-29 16:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Условие задачи')),
                ('correct_answer', models.FloatField(validators=[django.core.validators.MinValueValidator(-1000000), django.core.validators.MaxValueValidator(1000000)], verbose_name='Правильный ответ')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], default='medium', max_length=10, verbose_name='Сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.FloatField(verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно?')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='problems.problem', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Попытка',
                'verbose_name_plural': 'Попытки',
                'ordering': ['-timestamp'],
            },
        ),
    ]
