# Generated by Django 6.0.3 on 2026-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tolerance',
            field=models.FloatField(default=0.01, help_text='Allowed difference for float numerical answers', verbose_name='Tolerance (margin of error)'),
        ),
    ]
