# Generated by Django 6.0.3 on 2026-04-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_tag_options_alter_attempt_user_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tolerance',
            field=models.FloatField(default=0.0, help_text='Allowed difference for float numerical answers', verbose_name='Tolerance (margin of error)'),
        ),
    ]
